package at.jku.dke.inga.rules

// ------------------------------------ GLOBAL --------------------------------------
global org.apache.logging.log4j.Logger LOGGER

// ------------------------------------ IMPORT --------------------------------------
import org.apache.logging.log4j.Logger
import java.util.Map
import at.jku.dke.inga.rules.models.ResolveParameterModel
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.shared.operations.Operation

// ---------------------------------- FUNCTIONS -------------------------------------
function boolean isActionNumberParam(String s){
   try {
       Integer.valueOf(s);
       return true;
   } catch( Exception e ){
       return false;
   }
}

function int toActionNumberParam(String s){
   try {
       return Integer.valueOf(s);
   } catch(Exception e){
       return -1;
   }
}

// ------------------------------------ RULES ---------------------------------------
rule "Resolve Parameter"
    agenda-group "resolve-parameter"
when
    $model : ResolveParameterModel(isActionNumberParam(userInput), possibleValues.containsKey(toActionNumberParam(userInput)))
then
    LOGGER.debug("Parameter resolved");
    insert($model.getPossibleValues().get(toActionNumberParam($model.getUserInput())).getDisplayableId());
end