package at.jku.dke.inga.rules

// ------------------------------------ GLOBAL --------------------------------------
global at.jku.dke.inga.data.repositories.CubeLabelRepository cubeLabelRepository;

// ------------------------------------ IMPORT --------------------------------------
import java.util.Locale
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.inga.shared.display.ListDisplay
import at.jku.dke.inga.rules.models.ResolveValuesDataModel

// ------------------------------------ RULES ---------------------------------------
rule "Select cubes"
    agenda-group "value-determination"
when
    $model : ResolveValuesDataModel(operation == EventNames.NAVIGATE_CUBE_SELECT)
then
    insert(new ListDisplay("selectCube", $model.getLocale(), cubeLabelRepository.findByLang($model.getLanguage())));
end