package optaplanner

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.csp.domain.AnalysisSituationEntity
import at.jku.dke.ida.app.ruleset.helpers.CSPRuleHelpers
import org.optaplanner.core.api.score.buildin.hardsoftbigdecimal.HardSoftBigDecimalScoreHolder
import java.math.BigDecimal
import at.jku.dke.ida.app.ruleset.helpers.CSPRuleHelpers

// ------------------------------------ GLOBAL --------------------------------------
global HardSoftBigDecimalScoreHolder scoreHolder;

// ------------------------------------ RULES ---------------------------------------
// TODO: Rules that make sure all CoI and CoC values are in the same cubes