PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX qbx: <http://dke.jku.at/inga/cubes#>
PREFIX sim: <http://dke.jku.at/ida/similarity#>

INSERT {
    GRAPH sim:cube-assignment {
        ?mapping rdf:type sim:CubeAssignment ;
                 sim:cube ?cube ;
                 sim:from ?element .
    }
}
WHERE
{
    SELECT ?mapping ?cube ?element
    WHERE {
        ?cube qbx:measure ?measure .
        ?measure rdf:type qbx:BaseMeasure .

        ?aggMeasure rdf:type        qbx:AggregateMeasure ;
                    qbx:derivedFrom+ ?measure .

        ?element rdf:type   qbx:AggregateMeasurePredicate ;
                 qbx:over   ?aggMeasure .
        BIND(IRI(CONCAT("sim:mapping_", STRUUID())) AS ?mapping)
    }
}