PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX qbx: <http://dke.jku.at/inga/cubes#>
PREFIX sim: <http://dke.jku.at/ida/similarity#>

INSERT {
    GRAPH sim:cube-assignment {
        ?mapping rdf:type sim:CubeAssignment ;
                 sim:cube ?cube ;
                 sim:from ?element ;
                 sim:partOf ?part.
    }
}
WHERE
{
    {
        SELECT ?mapping ?cube ?element ?part
        WHERE {
            ?cube qbx:measure ?bmeasure .
            ?bmeasure rdf:type qbx:BaseMeasure .

            ?ameasure rdf:type        qbx:AggregateMeasure ;
                      qbx:derivedFrom ?bmeasure .

            ?cmeasure rdf:type        qbx:ComparativeMeasure ;
                      qbx:setOfInterestMeasure ?ameasure .

            ?element rdf:type        qbx:ComparativeMeasurePredicate ;
                     qbx:over 		 ?cmeasure .

            BIND('setOfInterest' AS ?part)
            BIND(IRI(CONCAT("sim:mapping_", STRUUID())) AS ?mapping)
        }
    }
    UNION
    {
        SELECT ?mapping ?cube ?element ?part
        WHERE {
            ?cube qbx:measure ?bmeasure .
            ?bmeasure rdf:type qbx:BaseMeasure .

            ?ameasure rdf:type        qbx:AggregateMeasure ;
                      qbx:derivedFrom ?bmeasure .

            ?cmeasure rdf:type        qbx:ComparativeMeasure ;
                      qbx:setOfComparisonMeasure ?ameasure .

            ?element rdf:type        qbx:ComparativeMeasurePredicate ;
                     qbx:over 		 ?cmeasure .

            BIND('setOfComparison' AS ?part)
            BIND(IRI(CONCAT("sim:mapping_", STRUUID())) AS ?mapping)
        }
    }
}