package core_rules.operation_intent

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.rules.models.OperationIntentServiceModel
import at.jku.dke.ida.rules.results.StringConfidenceResult
import at.jku.dke.ida.shared.EventNames
import at.jku.dke.ida.app.ruleset.interception.OperationInputIntentModel

// ------------------------------------ RULES ---------------------------------------
rule "ExecuteQuery Intent - 'execute' keyword"
    agenda-group "operation-intent-determination"
when
    $model : OperationIntentServiceModel(userInput.toLowerCase() contains "execute")
then
    insert(new StringConfidenceResult(EventNames.EXECUTE_QUERY, 0.5));
end

rule "ExecuteQuery Intent - 'execute' similarity"
    agenda-group "operation-intent-determination"
when
    $model : OperationInputIntentModel(topSimilarity != null && topSimilarity.getElement().getDisplayableId() == EventNames.EXECUTE_QUERY)
then
    insert(new StringConfidenceResult(EventNames.EXECUTE_QUERY, $model.getTopSimilarity().getScore()));
end