package core_rules.operation_intent

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.rules.interfaces.OperationIntentServiceModel
import at.jku.dke.ida.rules.results.EventConfidenceResult
import at.jku.dke.ida.app.ruleset.helpers.UserInput
import at.jku.dke.ida.shared.Event
import at.jku.dke.ida.app.ruleset.interception.models.OperationInputIntentModel

// ------------------------------------ RULES ---------------------------------------
rule "ExecuteOperation Intent Number"
    agenda-group "operation-intent-determination"
when
    $model : OperationIntentServiceModel(UserInput.isNumber(userInput))
then
    insert(new EventConfidenceResult(Event.NAVIGATE, 0.5));
end

rule "ExecuteOperation Intent Similarity"
    agenda-group "operation-intent-determination"
when
    $model : OperationInputIntentModel(topSimilarity != null)
then
    insert(new EventConfidenceResult(Event.NAVIGATE, $model.getTopSimilarity().getScore()));
end