package core_rules.operation_intent

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.rules.interfaces.OperationIntentServiceModel
import at.jku.dke.ida.rules.results.EventConfidenceResult
import at.jku.dke.ida.shared.Event
import org.apache.commons.lang3.math.NumberUtils
import at.jku.dke.ida.app.ruleset.interception.models.OperationInputIntentModel

// ------------------------------------ RULES ---------------------------------------
rule "ExecuteOperation Intent"
    agenda-group "operation-intent-determination"
when
    $model : OperationIntentServiceModel(NumberUtils.isParsable(userInput))
then
    insert(new EventConfidenceResult(Event.NAVIGATE, 1.0));
end

rule "ExecuteOperation Intent Similarity"
    agenda-group "operation-intent-determination"
when
    $model : OperationInputIntentModel(topSimilarity != null)
then
    insert(new EventConfidenceResult(Event.NAVIGATE, $model.getTopSimilarity().getScore()));
end
