package app_rules.operation_intent

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.rules.interfaces.OperationIntentServiceModel
import at.jku.dke.ida.rules.results.EventConfidenceResult
import at.jku.dke.ida.app.ruleset.helpers.UserInput
import at.jku.dke.ida.shared.Event
import at.jku.dke.ida.shared.operations.Operation
import at.jku.dke.ida.app.ruleset.interception.models.OperationInputIntentModel

// ------------------------------------ RULES ---------------------------------------
rule "SwitchIntent Intent - similarity"
    agenda-group "operation-intent-determination"
when
    $model : OperationInputIntentModel(topSimilarity != null && topSimilarity.getElement().getDisplayableId().startsWith(Event.SWITCH.getEventName()))
then
    insert(new EventConfidenceResult(((Operation)$model.getTopSimilarity().getElement()).getEvent(), $model.getTopSimilarity().getScore()));
end

rule "SwitchIntent Intent - position"
    agenda-group "operation-intent-determination"
when
    $model : OperationIntentServiceModel(UserInput.isNumber(userInput),
                                         possibleOperations.containsKey(UserInput.toInteger(userInput)),
                                         possibleOperations.get(UserInput.toInteger(userInput)).event.getEventName().startsWith(Event.SWITCH.getEventName()))
then
    insert(new EventConfidenceResult($model.getPossibleOperations().get(UserInput.toInteger($model.getUserInput())).getEvent(), 1.0));
end