package set_value

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.data.models.DimensionLabel
import at.jku.dke.inga.rules.models.SetValueServiceModel
import org.apache.commons.lang3.tuple.Pair

// ------------------------------------ RULES ---------------------------------------
rule "Add Slice Condition"
    agenda-group "set-value"
when
    $as : NonComparativeAnalysisSituation()
    $model : SetValueServiceModel(operation == EventNames.NAVIGATE_SLICE_CONDITION_NARROW, analysisSituation == $as, value instanceof DimensionLabel)
then
    $as.getDimensionQualification(((DimensionLabel)$model.getValue()).getDimensionUri()).addSliceCondition(((DimensionLabel)$model.getValue()).getUri());
end

rule "Drop Slice Condition"
    agenda-group "set-value"
when
    $as : NonComparativeAnalysisSituation()
    $model : SetValueServiceModel(operation == EventNames.NAVIGATE_SLICE_CONDITION_BROADEN, analysisSituation == $as, value instanceof DimensionLabel)
then
    $as.getDimensionQualification(((DimensionLabel)$model.getValue()).getDimensionUri()).removeSliceCondition(((DimensionLabel)$model.getValue()).getUri());
end

rule "Refocus Slice Condition"
    agenda-group "set-value"
when
    $as : NonComparativeAnalysisSituation()
    $model : SetValueServiceModel(operation == EventNames.NAVIGATE_SLICE_CONDITION_REFOCUS, analysisSituation == $as, value instanceof Pair)
then
    $as.getDimensionQualification(((Pair<DimensionLabel, DimensionLabel>)$model.getValue()).getLeft().getDimensionUri()).removeSliceCondition(((Pair<DimensionLabel, DimensionLabel>)$model.getValue()).getLeft().getUri());
    $as.getDimensionQualification(((Pair<DimensionLabel, DimensionLabel>)$model.getValue()).getRight().getDimensionUri()).addSliceCondition(((Pair<DimensionLabel, DimensionLabel>)$model.getValue()).getRight().getUri());
end