package at.jku.dke.inga.rules

// ------------------------------------ GLOBAL --------------------------------------
global org.apache.logging.log4j.Logger LOGGER

// ------------------------------------ IMPORT --------------------------------------
import org.apache.logging.log4j.Logger
import java.util.Map
import at.jku.dke.inga.rules.models.ResolveValueInputModel
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.shared.operations.Operation

// ---------------------------------- FUNCTIONS -------------------------------------
function boolean isVINumber(String s){
   try {
       Integer.valueOf(s);
       return true;
   } catch( Exception e ){
       return false;
   }
}

// ------------------------------------ RULES ---------------------------------------
rule "VI: ExitApplication Intent - 'exit' keyword"
    agenda-group "resolve-value-input"
when
    $model : ResolveValueInputModel(userInput.toLowerCase() contains "exit")
then
    LOGGER.debug("ExitApplication Intent resolved");
    insert(EventNames.EXIT);
end

rule "VI: ExecuteQuery Intent - 'execute' keyword"
    agenda-group "resolve-value-input"
when
    $model : ResolveValueInputModel(userInput.toLowerCase() contains "execute")
then
    LOGGER.debug("ExecuteQuery Intent resolved");
    insert(EventNames.EXECUTE_QUERY);
end

rule "VI: MoreInformation Intent - 'more' Keyword"
    agenda-group "resolve-value-input"
when
    $model : ResolveValueInputModel(userInput.toLowerCase() contains "more")
then
    LOGGER.debug("MoreInformation Intent resolved");
    insert(EventNames.MORE_INFORMATION);
end

rule "VI: SelectValue Intent"
    agenda-group "resolve-value-input"
when
    $model : ResolveValueInputModel(isVINumber(userInput))
then
    LOGGER.debug("SelectValue Intent resolved"); // TODO check if execute query option, then trigger it already here
    insert(EventNames.NAVIGATE);
end