package core_rules.value_intent

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.rules.interfaces.ValueIntentServiceModel
import at.jku.dke.ida.rules.results.EventConfidenceResult
import at.jku.dke.ida.shared.Event
import at.jku.dke.ida.app.ruleset.helpers.UserInput
import at.jku.dke.ida.app.ruleset.interception.models.ValueInputIntentModel

// ------------------------------------ RULES ---------------------------------------
rule "SelectValue Intent"
    agenda-group "value-intent-determination"
when
    $model : ValueIntentServiceModel(UserInput.isNumber(userInput))
then
    insert(new EventConfidenceResult(Event.NAVIGATE, 0.5));
end
rule "SelectValue Intent Similarity"
    agenda-group "value-intent-determination"
when
    $model : ValueInputIntentModel(topSimilarity != null)
    eval($model.getTopSimilarity().getElement().getDisplayableId() != Event.EXIT.getEventName() &&
         $model.getTopSimilarity().getElement().getDisplayableId() != Event.ABORT.getEventName())
then
    insert(new EventConfidenceResult(Event.NAVIGATE, $model.getTopSimilarity().getScore()));
end

rule "SelectValue Two values Intent"
    agenda-group "value-intent-determination"
when
    $model : ValueIntentServiceModel(UserInput.isTwoNumberSelection(userInput))
then
    insert(new EventConfidenceResult(Event.NAVIGATE, 0.5));
end
// two value intent similarity sowieso über selectvaluenothing