package operation_intent

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.rules.models.OperationIntentServiceModel
import at.jku.dke.inga.rules.results.StringConfidenceResult
import at.jku.dke.inga.shared.EventNames

// ------------------------------------ RULES ---------------------------------------
rule "ExecuteQuery Intent - 'execute' keyword"
    agenda-group "operation-intent-determination"
when
    $model : OperationIntentServiceModel(userInput.toLowerCase() contains "execute")
then
    insert(new StringConfidenceResult(EventNames.EXECUTE_QUERY, 0.5));
end