package core_rules.intent

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.rules.models.OperationIntentServiceModel
import at.jku.dke.ida.rules.results.StringConfidenceResult
import at.jku.dke.ida.shared.EventNames
import at.jku.dke.ida.app.ruleset.interception.OperationInputIntentModel
import at.jku.dke.ida.app.ruleset.interception.ValueInputIntentModel

// ------------------------------------ RULES ---------------------------------------
rule "ExitApplication Intent - 'exit' keyword"
    agenda-group "intent-determination"
when
    $model : OperationIntentServiceModel(userInput.toLowerCase() contains "exit")
then
    insert(new StringConfidenceResult(EventNames.EXIT, 0.5));
end

rule "ExitApplication Intent - 'exit' operation similarity"
    agenda-group "operation-intent-determination"
when
    $model : OperationInputIntentModel(topSimilarity != null && topSimilarity.getElement().getDisplayableId() == EventNames.EXIT)
then
    insert(new StringConfidenceResult(EventNames.EXIT, $model.getTopSimilarity().getScore()));
end

rule "ExitApplication Intent - 'exit' value similarity"
    agenda-group "value-intent-determination"
when
    $model : ValueInputIntentModel(topSimilarity != null && topSimilarity.getElement().getDisplayableId() == EventNames.EXIT)
then
    insert(new StringConfidenceResult(EventNames.EXIT, $model.getTopSimilarity().getScore()));
end