package core_rules.intent

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.rules.models.OperationIntentServiceModel
import at.jku.dke.ida.rules.results.StringConfidenceResult
import at.jku.dke.ida.shared.EventNames

// ------------------------------------ RULES ---------------------------------------
//rule "MoreInformation Intent - 'more' Keyword"
//    agenda-group "intent-determination"
//when
//    $model : OperationIntentServiceModel(userInput.toLowerCase() contains "more")
//then
//    insert(new StringConfidenceResult(EventNames.MORE_INFORMATION, 0.5));
//end