package app_rules.csp

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.shared.models.ComparativeAnalysisSituation
import at.jku.dke.ida.csp.domain.AnalysisSituationEntity
import at.jku.dke.ida.csp.models.FillDeterminedValuesServiceModel
import at.jku.dke.ida.app.ruleset.helpers.ValueSetter
import at.jku.dke.ida.data.models.CubeSimilarity
import at.jku.dke.ida.data.models.DimensionSimilarity
import java.util.stream.Collectors

// ------------------------------------ RULES ---------------------------------------