package app_rules.value_display

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.shared.Event
import at.jku.dke.ida.shared.display.ListDisplay
import at.jku.dke.ida.rules.interfaces.ValueDisplayServiceModel

// ------------------------------------ RULES ---------------------------------------
rule "Select cubes"
    agenda-group "value-display-determination"
when
    $model : ValueDisplayServiceModel(operation == Event.NAVIGATE_CUBE_SELECT)
then
    insert(new ListDisplay("selectCube", $model.getLocale(), $model.getCubeRepository().getAllLabelsByLang($model.getLanguage())));
end