package app_rules.value_display

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.shared.Event
import at.jku.dke.ida.shared.models.ComparativeAnalysisSituation
import at.jku.dke.ida.shared.display.ListDisplay
import at.jku.dke.ida.rules.interfaces.ValueDisplayServiceModel

// ------------------------------------ RULES ---------------------------------------
rule "Add Score - Select all scores, except the already selected ones"
    agenda-group "value-display-determination"
when
    $as : ComparativeAnalysisSituation()
    $model : ValueDisplayServiceModel(operation == Event.NAVIGATE_SCORE_ADD, analysisSituation == $as)
then
    insert(new ListDisplay(
        "addScore",
        $model.getLocale(),
        $model.getComparativeMeasureRepository().getLabelsByLangAndCube($model.getLanguage(), $as.getContextOfInterest().getCube(), $as.getScores())));
end

rule "Drop Score - Select all selected scores"
    agenda-group "value-display-determination"
when
    $as : ComparativeAnalysisSituation()
    $model : ValueDisplayServiceModel(operation == Event.NAVIGATE_SCORE_DROP, analysisSituation == $as)
then
    insert(new ListDisplay(
        "dropScore",
        $model.getLocale(),
        $model.getComparativeMeasureRepository().getLabelsByLangAndIris($model.getLanguage(), $as.getScores())));
end