package app_rules.value_display

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.shared.Event
import at.jku.dke.ida.shared.models.ComparativeAnalysisSituation
import at.jku.dke.ida.shared.display.ListDisplay
import at.jku.dke.ida.rules.interfaces.ValueDisplayServiceModel

// ------------------------------------ RULES ---------------------------------------
rule "Add Score Filter - Select all score filters, except the already selected ones"
    agenda-group "value-display-determination"
when
    $as : ComparativeAnalysisSituation()
    $model : ValueDisplayServiceModel(operation == Event.NAVIGATE_SCORE_FILTER_ADD, analysisSituation == $as)
then
    insert(new ListDisplay(
        "addScoreFilter",
        $model.getLocale(),
        $model.getComparativeMeasurePredicateRepository().getLabelsByLangAndCube($model.getLanguage(), $as.getContextOfInterest().getCube(), $as.getScoreFilters())));
end

rule "Drop Score Filter - Select all selected score filters"
    agenda-group "value-display-determination"
when
    $as : ComparativeAnalysisSituation()
    $model : ValueDisplayServiceModel(operation == Event.NAVIGATE_SCORE_FILTER_DROP, analysisSituation == $as)
then
    insert(new ListDisplay(
        "dropScoreFilter",
        $model.getLocale(),
        $model.getComparativeMeasurePredicateRepository().getLabelsByLangAndIris($model.getLanguage(), $as.getScoreFilters())));
end