package at.jku.dke.inga.rules

// ------------------------------------ GLOBAL --------------------------------------
global at.jku.dke.inga.data.repositories.CubeRepository cubeRepository;

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.shared.display.ListDisplay
import at.jku.dke.inga.rules.models.ValuesDisplayDeterminationServiceModel

// ------------------------------------ RULES ---------------------------------------
rule "Select cubes"
    agenda-group "values-display-determination"
when
    $model : ValuesDisplayDeterminationServiceModel(operation == EventNames.NAVIGATE_CUBE_SELECT)
then
    insert(new ListDisplay("selectCube", $model.getLocale(), cubeRepository.findLabelsByLang($model.getLanguage())));
end