package at.jku.dke.inga.rules

// ------------------------------------ GLOBAL --------------------------------------
global at.jku.dke.inga.data.repositories.GranularityLevelRepository granularityLevelRepository;

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.inga.shared.display.ListDisplay
import at.jku.dke.inga.shared.display.TwoListDisplay
import at.jku.dke.inga.rules.models.ValuesDisplayDeterminationServiceModel

// ------------------------------------ RULES ---------------------------------------
rule "Roll Up"
    agenda-group "values-display-determination"
when
    $as : NonComparativeAnalysisSituation()
    $model : ValuesDisplayDeterminationServiceModel(operation == EventNames.NAVIGATE_GL_ROLL_UP, analysisSituation == $as)
then
    insert(new ListDisplay(
        "rollUp",
        $model.getLocale(),
        granularityLevelRepository.findParentLevels($as.getCube(), $model.getLanguage(), $as.getDimensionQualifications())));
end

rule "Drill Down"
    agenda-group "values-display-determination"
when
    $as : NonComparativeAnalysisSituation()
    $model : ValuesDisplayDeterminationServiceModel(operation == EventNames.NAVIGATE_GL_DRILL_DOWN, analysisSituation == $as)
then
    insert(new ListDisplay(
        "drillDown",
        $model.getLocale(),
        granularityLevelRepository.findChildLevels($as.getCube(), $model.getLanguage(), $as.getDimensionQualifications())));
end