package app_rules.set_value

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.ida.shared.Event
import at.jku.dke.ida.data.models.labels.Label
import at.jku.dke.ida.data.models.labels.DimensionLevelLabel
import at.jku.dke.ida.rules.interfaces.SetValueServiceModel
import org.apache.commons.lang3.tuple.Pair
import at.jku.dke.ida.app.ruleset.helpers.Constants
import at.jku.dke.ida.data.models.labels.DimensionLevelLabel
import at.jku.dke.ida.data.models.labels.Label

// ------------------------------------ RULES ---------------------------------------
rule "Add Dice Node"
    agenda-group "set-value"
when
    $as : NonComparativeAnalysisSituation()
    $model : SetValueServiceModel(operation == Event.NAVIGATE_DICE_NODE_MOVE_DOWN, analysisSituation == $as, value instanceof DimensionLevelLabel)
then
    $as.getDimensionQualification(((DimensionLevelLabel)$model.getValue()).getDimensionUri()).setDiceNode(((DimensionLevelLabel)$model.getValue()).getUri());
    $as.getDimensionQualification(((DimensionLevelLabel)$model.getValue()).getDimensionUri()).setDiceLevel(((DimensionLevelLabel)$model.getValue()).getLevelUri());
    $model.removeAdditionalData(Constants.ADD_DATA_DIMENSION);
    $model.removeAdditionalData(Constants.ADD_DATA_LEVEL);
end

rule "Drop Dice Node"
    agenda-group "set-value"
when
    $as : NonComparativeAnalysisSituation()
    $model : SetValueServiceModel(operation == Event.NAVIGATE_DICE_NODE_MOVE_UP, analysisSituation == $as, value instanceof Label)
then
    $as.getDimensionQualification(((Label)$model.getValue()).getUri()).setDiceLevel(null);
    $as.getDimensionQualification(((Label)$model.getValue()).getUri()).setDiceNode(null);
    $model.removeAdditionalData(Constants.ADD_DATA_DIMENSION);
    $model.removeAdditionalData(Constants.ADD_DATA_LEVEL);
end