package app_rules.set_value

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.shared.models.ComparativeAnalysisSituation
import at.jku.dke.ida.shared.Event
import at.jku.dke.ida.shared.display.Displayable
import at.jku.dke.ida.rules.interfaces.SetValueServiceModel
import org.apache.commons.lang3.tuple.Pair

// ------------------------------------ RULES ---------------------------------------
rule "Add score"
    agenda-group "set-value"
when
    $as : ComparativeAnalysisSituation()
    $model : SetValueServiceModel(operation == Event.NAVIGATE_SCORE_ADD, analysisSituation == $as, value instanceof Displayable)
then
    $as.addScore(((Displayable)$model.getValue()).getDisplayableId());
end

rule "Drop score"
    agenda-group "set-value"
when
    $as : ComparativeAnalysisSituation()
    $model : SetValueServiceModel(operation == Event.NAVIGATE_SCORE_DROP, analysisSituation == $as, value instanceof Displayable)
then
    $as.removeScore(((Displayable)$model.getValue()).getDisplayableId());
end