PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX wordnet: <http://wordnet-rdf.princeton.edu/ontology#>
PREFIX sim: <http://dke.jku.at/inga/similarity#>

SELECT DISTINCT ?documentID ?documentText WHERE {
    {
        SELECT DISTINCT ?term ?text WHERE {
            GRAPH sim:wordnet {
                ?term ontolex:canonicalForm ?canonicalForm .
                ?term wordnet:partOfSpeech wordnet:noun .
                ?term ontolex:sense ?lexicalizedSense .
                ?lexicalizedSense ontolex:isLexicalizedSenseOf ?sense .
                {
                    ?canonicalForm ontolex:writtenRep ?text .
                } UNION {
                    ?sense wordnet:definition ?definition .
                    ?definition rdf:value ?text .
                }
            }
        }
    } UNION {
        SELECT DISTINCT ?term ?text WHERE {
            GRAPH sim:wordnet {
                ?term ontolex:canonicalForm?canonicalForm .
                ?term wordnet:partOfSpeech wordnet:noun .
                ?term ontolex:sense ?lexicalizedSense .
                ?lexicalizedSense ontolex:isLexicalizedSenseOf ?sense .
                ?sense wordnet:hyponym ?hyponym .
                {
                    ?hyponymLexicalizedSense ontolex:isLexicalizedSenseOf ?hyponym .
                    ?hyponymTerm ontolex:sense ?hyponymLexicalizedSense .
                    ?hyponymTerm ontolex:canonicalForm ?hyponymCanonicalForm .
                    ?hyponymCanonicalForm  ontolex:writtenRep ?text .
                } UNION {
                    ?hyponym wordnet:definition ?hyponymDefinition .
                    ?hyponymDefinition rdf:value ?text .
                }
            }
        }
    }
    BIND(?term AS ?documentID)
    BIND(?text AS ?documentText)
}