package value_display

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.inga.shared.display.ListDisplay
import at.jku.dke.inga.shared.display.TwoListDisplay
import at.jku.dke.inga.rules.models.ValueDisplayServiceModel

// ------------------------------------ RULES ---------------------------------------
rule "Roll Up - All parent levels"
    agenda-group "value-display-determination"
when
    $as : NonComparativeAnalysisSituation()
    $model : ValueDisplayServiceModel(operation == EventNames.NAVIGATE_GL_ROLL_UP, analysisSituation == $as)
then
    insert(new ListDisplay(
        "rollUp",
        $model.getLocale(),
        $model.getGranularityLevelRepository().getParentLevelLabelsByLangAndCube($model.getLanguage(), $as.getCube(), $as.getDimensionQualifications())));
end

rule "Drill Down - All child levels"
    agenda-group "value-display-determination"
when
    $as : NonComparativeAnalysisSituation()
    $model : ValueDisplayServiceModel(operation == EventNames.NAVIGATE_GL_DRILL_DOWN, analysisSituation == $as)
then
    insert(new ListDisplay(
        "drillDown",
        $model.getLocale(),
        $model.getGranularityLevelRepository().getChildLevelLabelsByLangAndCube($model.getLanguage(), $as.getCube(), $as.getDimensionQualifications())));
end