package core_rules.operation_display

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.shared.Event
import at.jku.dke.ida.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.ida.shared.operations.Operation
import at.jku.dke.ida.rules.interfaces.OperationDisplayServiceModel

// ---------------------- BASE MEASURE CONDITION OPERATIONS -------------------------
rule "'Add Base Measure Condition' - if at least one predicate is available"
    agenda-group "operation-display-determination"
when
    $model : OperationDisplayServiceModel(areNotSelectedBaseMeasureConditionsAvailable())
then
    insert(new Operation(Event.NAVIGATE_BMC_NARROW, $model.getLocale(), 50));
end

//rule "'Narrow Base Measure Condition' - if "
//    agenda-group "operation-display-determination"
//    enabled false
//when
//then
//end

rule "'Drop Base Measure Condition' - if at least one predicate is selected"
    agenda-group "operation-display-determination"
when
    $as : NonComparativeAnalysisSituation(baseMeasureConditions.isEmpty() == false)
    $model : OperationDisplayServiceModel(analysisSituation == $as)
then
    insert(new Operation(Event.NAVIGATE_BMC_BROADEN, $model.getLocale(), 52));
end

//rule "'Broaden Base Measure Condition' - if "
//    agenda-group "operation-display-determination"
//    enabled false
//when
//then
//end

rule "'Refocus Base Measure Condition' - if at least one predicate is selected and one available"
    agenda-group "operation-display-determination"
    enabled false
when
    $as : NonComparativeAnalysisSituation(baseMeasureConditions.isEmpty() == false)
    $model : OperationDisplayServiceModel(areNotSelectedBaseMeasureConditionsAvailable(), analysisSituation == $as)
then
    insert(new Operation(Event.NAVIGATE_BMC_REFOCUS, $model.getLocale(), 51));
end