package core_rules.operation_display

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.shared.EventNames
import at.jku.dke.ida.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.ida.shared.operations.Operation
import at.jku.dke.ida.rules.models.OperationDisplayServiceModel

// ----------------------------- DICE NODE OPERATIONS -------------------------------
rule "'Move Down To Node' - if "
    agenda-group "operation-display-determination"
    enabled false
when
    //$as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    //$model : OperationDisplayServiceModel(notSelectedMeasures.isEmpty() == false)
then
    //insert(new Operation(EventNames., 30));
end

rule "'Move Up To Node' - if "
    agenda-group "operation-display-determination"
    enabled false
when
    //$as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    //$model : OperationDisplayServiceModel(notSelectedMeasures.isEmpty() == false)
then
    //insert(new Operation(EventNames., 31));
end