package core_rules.operation_display

// ------------------------- IMPORT ------------------------------
import at.jku.dke.ida.shared.Event
import at.jku.dke.ida.shared.models.AnalysisSituation
import at.jku.dke.ida.shared.operations.Operation
import at.jku.dke.ida.rules.interfaces.OperationDisplayServiceModel

// ------------------- GENERAL OPERATIONS ------------------------
rule "'Exit' - Always"
    salience Integer.MAX_VALUE
    agenda-group "operation-display-determination"
when
    $model : OperationDisplayServiceModel()
then
    insert(new Operation(Event.EXIT, $model.getLocale(), Integer.MIN_VALUE));
end

// --------------------- AS OPERATIONS --------------------------
rule "'Select Cube' - if there is not already a selected cube"
    salience Integer.MAX_VALUE - 1
    agenda-group "operation-display-determination"
when
    $as : AnalysisSituation(isCubeDefined() == false)
    $model : OperationDisplayServiceModel(analysisSituation == $as)
then
    insert(new Operation(Event.NAVIGATE_CUBE_SELECT, $model.getLocale(), Integer.MAX_VALUE));
    drools.halt();
end

rule "'Execute Query' - if there is already a selected cube"
    agenda-group "operation-display-determination"
when
    $as : AnalysisSituation(isExecutable() == true)
    $model : OperationDisplayServiceModel(analysisSituation == $as)
then
    insert(new Operation(Event.EXECUTE_QUERY, $model.getLocale(), Integer.MAX_VALUE - 1));
end