package core_rules.operation_display

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.shared.Event
import at.jku.dke.ida.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.ida.shared.operations.Operation
import at.jku.dke.ida.rules.interfaces.OperationDisplayServiceModel

// ------------------------------ MEASURE OPERATIONS --------------------------------
rule "'Add Measure' - if at least one measure is available"
    agenda-group "operation-display-determination"
when
    $model : OperationDisplayServiceModel(isNotSelectedMeasureAvailable())
then
    insert(new Operation(Event.NAVIGATE_MEASURE_ADD, $model.getLocale(), 10));
end

rule "'Refocus Measure' - if at least one measure is available and one selected"
    agenda-group "operation-display-determination"
when
    $as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    $model : OperationDisplayServiceModel(isNotSelectedMeasureAvailable(), analysisSituation == $as)
then
    insert(new Operation(Event.NAVIGATE_MEASURE_REFOCUS, $model.getLocale(), 11));
end

rule "'Drop Measure' - if at least one measure is selected"
    agenda-group "operation-display-determination"
when
    $as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    $model : OperationDisplayServiceModel(analysisSituation == $as)
then
    insert(new Operation(Event.NAVIGATE_MEASURE_DROP, $model.getLocale(), 14));
end