package operation_display

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.inga.shared.operations.Operation
import at.jku.dke.inga.rules.models.OperationDisplayServiceModel

// ---------------------- BASE MEASURE CONDITION OPERATIONS -------------------------
rule "'Add Base Measure Condition' - if at least one predicate is available"
    agenda-group "operation-display-determination"
when
    $model : OperationDisplayServiceModel(notSelectedBaseMeasureConditions.isEmpty() == false)
then
    insert(new Operation(EventNames.NAVIGATE_BMC_NARROW, 50));
end

//rule "'Narrow Base Measure Condition' - if "
//    agenda-group "operation-display-determination"
//    enabled false
//when
//then
//end

rule "'Drop Base Measure Condition' - if at least one predicate is selected"
    agenda-group "operation-display-determination"
when
    $as : NonComparativeAnalysisSituation(baseMeasureConditions.isEmpty() == false)
    $model : OperationDisplayServiceModel(analysisSituation == $as)
then
    insert(new Operation(EventNames.NAVIGATE_BMC_BROADEN, 52));
end

//rule "'Broaden Base Measure Condition' - if "
//    agenda-group "operation-display-determination"
//    enabled false
//when
//then
//end

rule "'Refocus Base Measure Condition' - if at least one predicate is selected and one available"
    agenda-group "operation-display-determination"
    enabled false
when
    $as : NonComparativeAnalysisSituation(baseMeasureConditions.isEmpty() == false)
    $model : OperationDisplayServiceModel(notSelectedBaseMeasureConditions.isEmpty() == false, analysisSituation == $as)
then
    insert(new Operation(EventNames.NAVIGATE_BMC_REFOCUS, 51));
end