package operation_display

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.inga.shared.operations.Operation
import at.jku.dke.inga.rules.models.OperationDisplayServiceModel

// ------------------------------ FILTER OPERATIONS --------------------------------
rule "'Narrow Filter' - if "
    agenda-group "operation-display-determination"
    enabled false
when
    //$as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    //$model : OperationDisplayServiceModel(notSelectedMeasures.isEmpty() == false)
then
    //insert(new Operation(EventNames., 60));
end

rule "'Broaden Filter' - if "
    agenda-group "operation-display-determination"
    enabled false
when
    //$as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    //$model : OperationDisplayServiceModel(notSelectedMeasures.isEmpty() == false)
then
    //insert(new Operation(EventNames., 61));
end

rule "'Refocus Filter' - if "
    agenda-group "operation-display-determination"
    enabled false
when
    //$as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    //$model : OperationDisplayServiceModel(notSelectedMeasures.isEmpty() == false)
then
    //insert(new Operation(EventNames., 62));
end