package at.jku.dke.inga.rules

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.rules.models.ValueIntentDeterminationServiceModel
import at.jku.dke.inga.rules.results.StringValueConfidenceResult
import at.jku.dke.inga.rules.helpers.UserInput
import at.jku.dke.inga.shared.EventNames

// ------------------------------------ RULES ---------------------------------------
rule "SelectValue Intent"
    agenda-group "value-intent-determination"
when
    $model : ValueIntentDeterminationServiceModel(UserInput.isNumber(userInput))
then
    insert(new StringValueConfidenceResult(EventNames.NAVIGATE, 0.5));
end

rule "SelectValue Two values Intent"
    agenda-group "value-intent-determination"
when
    $model : ValueIntentDeterminationServiceModel(UserInput.isTwoNumberSelection(userInput))
then
    insert(new StringValueConfidenceResult(EventNames.NAVIGATE, 0.5));
end