package core_rules.set_value

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.ida.shared.EventNames
import at.jku.dke.ida.shared.display.Displayable
import at.jku.dke.ida.rules.models.SetValueServiceModel
import org.apache.commons.lang3.tuple.Pair

// ------------------------------------ RULES ---------------------------------------
rule "Add base measure condition"
    agenda-group "set-value"
when
    $as : NonComparativeAnalysisSituation()
    $model : SetValueServiceModel(operation == EventNames.NAVIGATE_BMC_NARROW, analysisSituation == $as, value instanceof Displayable)
then
    $as.addBaseMeasureCondition(((Displayable)$model.getValue()).getDisplayableId());
end

rule "Drop base measure condition"
    agenda-group "set-value"
when
    $as : NonComparativeAnalysisSituation()
    $model : SetValueServiceModel(operation == EventNames.NAVIGATE_BMC_BROADEN, analysisSituation == $as, value instanceof Displayable)
then
    $as.removeBaseMeasureCondition(((Displayable)$model.getValue()).getDisplayableId());
end

rule "Refocus base measure condition"
    agenda-group "set-value"
when
    $as : NonComparativeAnalysisSituation()
    $model : SetValueServiceModel(operation == EventNames.NAVIGATE_BMC_REFOCUS, analysisSituation == $as, value instanceof Pair)
then
    $as.addBaseMeasureCondition(((Pair<Displayable, Displayable>)$model.getValue()).getLeft().getDisplayableId());
    $as.removeBaseMeasureCondition(((Pair<Displayable, Displayable>)$model.getValue()).getRight().getDisplayableId());
end