package core_rules.set_value

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.data.models.DimensionLabel
import at.jku.dke.inga.rules.models.SetValueServiceModel

// ------------------------------------ RULES ---------------------------------------
rule "Roll Up"
    agenda-group "set-value"
when
    $as : NonComparativeAnalysisSituation()
    $model : SetValueServiceModel(operation == EventNames.NAVIGATE_GL_ROLL_UP, analysisSituation == $as, value instanceof DimensionLabel)
then
    $as.getDimensionQualification(((DimensionLabel)$model.getValue()).getDimensionUri()).setGranularityLevel(((DimensionLabel)$model.getValue()).getUri());
end

rule "Drill Down"
    agenda-group "set-value"
when
    $as : NonComparativeAnalysisSituation()
    $model : SetValueServiceModel(operation == EventNames.NAVIGATE_GL_DRILL_DOWN, analysisSituation == $as, value instanceof DimensionLabel)
then
    $as.getDimensionQualification(((DimensionLabel)$model.getValue()).getDimensionUri()).setGranularityLevel(((DimensionLabel)$model.getValue()).getUri());
end