package intent

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.rules.models.OperationIntentServiceModel
import at.jku.dke.inga.rules.results.StringConfidenceResult
import at.jku.dke.inga.shared.EventNames

// ------------------------------------ RULES ---------------------------------------
rule "ExitApplication Intent - 'exit' keyword"
    agenda-group "intent-determination"
when
    $model : OperationIntentServiceModel(userInput.toLowerCase() contains "exit")
then
    insert(new StringConfidenceResult(EventNames.EXIT, 0.5));
end