package at.jku.dke.inga.rules

// ------------------------------------ GLOBAL --------------------------------------
global org.apache.logging.log4j.Logger LOGGER

// ------------------------------------ IMPORT --------------------------------------
import org.apache.logging.log4j.Logger
import java.util.Map
import at.jku.dke.inga.rules.models.ResolveOperationInputModel
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.shared.operations.Operation

// ---------------------------------- FUNCTIONS -------------------------------------
function boolean isNumber(String s){
   try {
       Integer.valueOf(s);
       return true;
   } catch( Exception e ){
       return false;
   }
}

// ------------------------------------ RULES ---------------------------------------
rule "ExitApplication Intent - 'exit' keyword"
    agenda-group "resolve-operation-input"
when
    $model : ResolveOperationInputModel(userInput.toLowerCase() contains "exit")
then
    LOGGER.debug("ExitApplication Intent resolved");
    insert(EventNames.EXIT);
end

rule "ExecuteQuery Intent - 'execute' keyword"
    agenda-group "resolve-operation-input"
when
    $model : ResolveOperationInputModel(userInput.toLowerCase() contains "execute")
then
    LOGGER.debug("ExecuteQuery Intent resolved");
    insert(EventNames.EXECUTE_QUERY);
end

rule "MoreInformation Intent - 'more' Keyword"
    agenda-group "resolve-operation-input"
when
    $model : ResolveOperationInputModel(userInput.toLowerCase() contains "more")
then
    LOGGER.debug("MoreInformation Intent resolved");
    insert(EventNames.MORE_INFORMATION);
end

rule "ExecuteOperation Intent"
    agenda-group "resolve-operation-input"
when
    $model : ResolveOperationInputModel(isNumber(userInput))
then
    LOGGER.debug("ExecuteOperation Intent resolved"); // TODO check if execute query option, then trigger it already here
    insert(EventNames.NAVIGATE);
end