package app_rules.operation_display

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.shared.Event
import at.jku.dke.ida.shared.models.ComparativeAnalysisSituation
import at.jku.dke.ida.shared.operations.Operation
import at.jku.dke.ida.rules.interfaces.OperationDisplayServiceModel

// ------------------------------ JOIN CONDITION OPERATIONS --------------------------------
rule "'Add Join Condition' - if at least one join condition is available"
    agenda-group "operation-display-determination"
when
    $as : ComparativeAnalysisSituation()
    $model : OperationDisplayServiceModel(isNotSelectedJoinConditionAvailable())
then
    insert(new Operation(Event.NAVIGATE_JOIN_CONDITION_ADD, $model.getLocale(), 10));
end

rule "'Drop Join Condition' - if at least one join condition is selected"
    agenda-group "operation-display-determination"
when
    $as : ComparativeAnalysisSituation(joinConditions.isEmpty() == false)
    $model : OperationDisplayServiceModel(analysisSituation == $as)
then
    insert(new Operation(Event.NAVIGATE_JOIN_CONDITION_DROP, $model.getLocale(), 11));
end