package app_rules.operation_display

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.shared.Event
import at.jku.dke.ida.shared.models.ComparativeAnalysisSituation
import at.jku.dke.ida.shared.operations.Operation
import at.jku.dke.ida.rules.interfaces.OperationDisplayServiceModel

// ------------------------------ SCORE OPERATIONS --------------------------------
rule "'Add Score Filter' - if at least one score filter is available"
    agenda-group "operation-display-determination"
when
    $as : ComparativeAnalysisSituation()
    $model : OperationDisplayServiceModel(isNotSelectedScoreFilterAvailable())
then
    insert(new Operation(Event.NAVIGATE_SCORE_FILTER_ADD, $model.getLocale(), 30));
end

rule "'Drop Score Filter' - if at least one score filter is selected"
    agenda-group "operation-display-determination"
when
    $as : ComparativeAnalysisSituation(scoreFilters.isEmpty() == false)
    $model : OperationDisplayServiceModel(analysisSituation == $as)
then
    insert(new Operation(Event.NAVIGATE_SCORE_FILTER_DROP, $model.getLocale(), 31));
end