package core_rules.operation_display

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.shared.Event
import at.jku.dke.ida.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.ida.shared.operations.Operation
import at.jku.dke.ida.rules.interfaces.OperationDisplayServiceModel

// -------------------------- SLICE CONDITION OPERATIONS ----------------------------
rule "'Narrow Slice Condition' - if implies relationship available"
    agenda-group "operation-display-determination"
when
    $model : OperationDisplayServiceModel(isImplyRelationshipForSliceConditionAvailable())
then
    insert(new Operation(Event.NAVIGATE_SLICE_CONDITION_NARROW, $model.getLocale(), 40));
end

rule "'Broaden Slice Condition' - if subsumes relationship available"
    agenda-group "operation-display-determination"
when
    $model : OperationDisplayServiceModel(isSubsumeRelationshipForSliceConditionAvailable())
then
    insert(new Operation(Event.NAVIGATE_SLICE_CONDITION_BROADEN, $model.getLocale(), 42));
end

rule "'Refocus Slice Condition' - if at least one selected an one not selected"
    agenda-group "operation-display-determination"
when
    $model : OperationDisplayServiceModel(isDimensionWithSelectedAndNotSelectedSliceConditionsAvailable())
then
    insert(new Operation(Event.NAVIGATE_SLICE_CONDITION_REFOCUS, $model.getLocale(), 41));
end