package initial_sentence

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.app.ruleset.drools.InitialSentenceModel
import at.jku.dke.inga.app.ruleset.helpers.InitialSentenceHelper
import at.jku.dke.inga.data.models.Similarity

// ------------------------------------ RULES ---------------------------------------
rule "Initial Sentence - Exact word match"
    agenda-group "initial-sentence"
    enabled false
when
    $model : InitialSentenceModel()
    eval(InitialSentenceHelper.hasExactMatches($model))
then
    for(Similarity similarity : InitialSentenceHelper.exactMatches($model)) {
        insert(similarity);
    }
end
