package core_rules.set_value

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.shared.models.ComparativeAnalysisSituation
import at.jku.dke.ida.shared.Event
import at.jku.dke.ida.shared.display.Displayable
import at.jku.dke.ida.rules.interfaces.SetValueServiceModel
import org.apache.commons.lang3.tuple.Pair

// ------------------------------------ RULES ---------------------------------------
rule "Add join condition"
    agenda-group "set-value"
when
    $as : ComparativeAnalysisSituation()
    $model : SetValueServiceModel(operation == Event.NAVIGATE_JOIN_CONDITION_ADD, analysisSituation == $as, value instanceof Displayable)
then
    $as.addJoinCondition(((Displayable)$model.getValue()).getDisplayableId());
end

rule "Drop join condition"
    agenda-group "set-value"
when
    $as : ComparativeAnalysisSituation()
    $model : SetValueServiceModel(operation == Event.NAVIGATE_JOIN_CONDITION_DROP, analysisSituation == $as, value instanceof Displayable)
then
    $as.removeJoinCondition(((Displayable)$model.getValue()).getDisplayableId());
end