package at.jku.dke.inga.rules

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.rules.models.OperationIntentDeterminationServiceModel
import at.jku.dke.inga.rules.helpers.ConfidenceResult
import at.jku.dke.inga.shared.EventNames

// ------------------------------------ RULES ---------------------------------------
rule "ExitApplication Intent - 'exit' keyword"
    agenda-group "intent-determination"
when
    $model : OperationIntentDeterminationServiceModel(userInput.toLowerCase() contains "exit")
then
    insert(new ConfidenceResult(EventNames.EXIT, 0.5));
end