package at.jku.dke.inga.rules

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.rules.models.OperationIntentDeterminationServiceModel
import at.jku.dke.inga.rules.helpers.ConfidenceResult
import at.jku.dke.inga.shared.EventNames

// ------------------------------------ RULES ---------------------------------------
rule "MoreInformation Intent - 'more' Keyword"
    agenda-group "intent-determination"
when
    $model : OperationIntentDeterminationServiceModel(userInput.toLowerCase() contains "more")
then
    insert(new ConfidenceResult(EventNames.MORE_INFORMATION, 0.5));
end