package at.jku.dke.inga.rules

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.inga.shared.operations.Operation
import at.jku.dke.inga.rules.models.OperationDisplayDeterminationServiceModel

// ------------------------- GRANULARITY LEVEL OPERATIONS ----------------------------
rule "'Drill Down To Level' - if drill down relationships available"
    agenda-group "operations-display-determination"
when
    $as : NonComparativeAnalysisSituation()
    $model : OperationDisplayDeterminationServiceModel(nextDrillDownLevels.isEmpty() == false)
then
    insert(new Operation(EventNames.NAVIGATE_GL_DRILL_DOWN, $model.getLocale(), 20));
end

rule "'Roll Up To Level' - if roll up relationships available"
    agenda-group "operations-display-determination"
when
    $as : NonComparativeAnalysisSituation()
    $model : OperationDisplayDeterminationServiceModel(nextRollUpLevels.isEmpty() == false)
then
    insert(new Operation(EventNames.NAVIGATE_GL_ROLL_UP, 21));
end