package at.jku.dke.inga.rules

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.inga.shared.operations.Operation
import at.jku.dke.inga.rules.models.OperationDisplayDeterminationServiceModel

// -------------------------- SLICE CONDITION OPERATIONS ----------------------------
rule "'Narrow Slice Condition' - if "
    agenda-group "operations-display-determination"
    enabled false
when
    //$as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    //$model : ResolveOperationsDataModel(notSelectedMeasures.isEmpty() == false)
then
    //insert(new Operation(EventNames., 40));
end

rule "'Broaden Slice Condition' - if "
    agenda-group "operations-display-determination"
    enabled false
when
    //$as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    //$model : ResolveOperationsDataModel(notSelectedMeasures.isEmpty() == false)
then
    //insert(new Operation(EventNames., 41));
end

rule "'Refocus Slice Condition' - if "
    agenda-group "operations-display-determination"
    enabled false
when
    //$as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    //$model : ResolveOperationsDataModel(notSelectedMeasures.isEmpty() == false)
then
    //insert(new Operation(EventNames., 42));
end