package at.jku.dke.inga.rules

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.inga.shared.operations.Operation
import at.jku.dke.inga.rules.models.OperationDisplayDeterminationServiceModel

// ---------------------- BASE MEASURE CONDITION OPERATIONS -------------------------
rule "'Narrow Base Measure Condition' - if "
    agenda-group "possible-operations-determination"
    enabled false
when
    //$as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    //$model : ResolveOperationsDataModel(notSelectedMeasures.isEmpty() == false)
then
    //insert(new Operation(EventNames., 50));
end

rule "'Broaden Base Measure Condition' - if "
    agenda-group "possible-operations-determination"
    enabled false
when
    //$as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    //$model : ResolveOperationsDataModel(notSelectedMeasures.isEmpty() == false)
then
    //insert(new Operation(EventNames., 51));
end

rule "'Refocus Base Measure Condition' - if "
    agenda-group "possible-operations-determination"
    enabled false
when
    //$as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    //$model : ResolveOperationsDataModel(notSelectedMeasures.isEmpty() == false)
then
    //insert(new Operation(EventNames., 52));
end