package at.jku.dke.inga.rules

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.inga.shared.operations.Operation
import at.jku.dke.inga.rules.models.OperationDisplayDeterminationServiceModel

// ----------------------------- DICE NODE OPERATIONS -------------------------------
rule "'Move Down To Node' - if "
    agenda-group "possible-operations-determination"
    enabled false
when
    //$as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    //$model : ResolveOperationsDataModel(notSelectedMeasures.isEmpty() == false)
then
    //insert(new Operation(EventNames., 30));
end

rule "'Move Up To Node' - if "
    agenda-group "possible-operations-determination"
    enabled false
when
    //$as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    //$model : ResolveOperationsDataModel(notSelectedMeasures.isEmpty() == false)
then
    //insert(new Operation(EventNames., 31));
end

rule "'Move Aside To Node' - if "
    agenda-group "possible-operations-determination"
    enabled false
when
    //$as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    //$model : ResolveOperationsDataModel(notSelectedMeasures.isEmpty() == false)
then
    //insert(new Operation(EventNames., 32));
end

rule "'Move To Node' - if "
    agenda-group "possible-operations-determination"
    enabled false
when
    //$as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    //$model : ResolveOperationsDataModel(notSelectedMeasures.isEmpty() == false)
then
    //insert(new Operation(EventNames., 33));
end