PREFIX : <http://www.ontotext.com/graphdb/similarity/>
PREFIX inst: <http://www.ontotext.com/graphdb/similarity/instance/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX qbx: <http://dke.jku.at/inga/cubes#>
PREFIX sim: <http://dke.jku.at/inga/similarity#>

INSERT {
    GRAPH sim:wordnet-scores-en {
        ?mapping rdf:type sim:Mapping ;
                 sim:inCube   ?cube ;
                 sim:from     ?element ;
                 sim:to       ?documentID ;
                 sim:hasScore ?score ;
                 sim:fromType qbx:AggregateMeasurePredicate.
    }
}
WHERE
{
    SELECT ?mapping ?cube ?element ?documentID ?score
    WHERE {
        ?search a inst:wordnet ;
                :searchTerm         ?filterText ;
                :searchParameters   "" ;
                :documentResult     ?result .
        ?result :value ?documentID ;
                :score ?score .
        {
            SELECT ?cube ?element ?filterText
            WHERE {
                ?cube qbx:measure ?measure .
                ?measure rdf:type qbx:BaseMeasure .

                ?aggMeasure rdf:type        qbx:AggregateMeasure ;
                            qbx:derivedFrom+ ?measure .

                ?element rdf:type   qbx:AggregateMeasurePredicate ;
                         qbx:over   ?aggMeasure ;
                         rdfs:label ?filterText.

                FILTER(isLiteral(?filterText)) .
                FILTER(lang(?filterText) = "en") .
            }
        }
        BIND(IRI(CONCAT("sim:mapping_", STRUUID())) AS ?mapping)
    }
}