package core_rules.pattern

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.ida.rules.interfaces.PatternServiceModel
import at.jku.dke.ida.rules.results.StringConfidenceResult
import at.jku.dke.ida.shared.operations.Pattern

// ------------------------------------ RULES ---------------------------------------
rule "Comparative Pattern - keyword"
    agenda-group "pattern-determination"
    salience 10
when
    $model : PatternServiceModel(userInput != null, getUserInput().toLowerCase().contains("compare"))
then
    insert(new StringConfidenceResult(Pattern.COMPARATIVE));
end

rule "Non comparative pattern"
    agenda-group "pattern-determination"
    salience 0
when
    not StringConfidenceResult()
then
    insert(new StringConfidenceResult(Pattern.NONCOMPARATIVE));
end