package at.jku.dke.inga.rules

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.rules.models.OperationIntentDeterminationServiceModel
import at.jku.dke.inga.rules.results.StringValueConfidenceResult
import at.jku.dke.inga.shared.EventNames

// ------------------------------------ RULES ---------------------------------------
rule "ExecuteQuery Intent - 'execute' keyword"
    agenda-group "operation-intent-determination"
when
    $model : OperationIntentDeterminationServiceModel(userInput.toLowerCase() contains "execute")
then
    insert(new StringValueConfidenceResult(EventNames.EXECUTE_QUERY, 0.5));
end