package at.jku.dke.inga.rules
// ------------------------------------ IMPORT --------------------------------------

import at.jku.dke.inga.rules.models.OperationIntentDeterminationServiceModel
import at.jku.dke.inga.rules.helpers.ConfidenceResult
import at.jku.dke.inga.shared.EventNames
import org.apache.commons.lang3.math.NumberUtils

// ------------------------------------ RULES ---------------------------------------
rule "ExecuteOperation Intent"
    agenda-group "operation-intent-determination"
when
    $model : OperationIntentDeterminationServiceModel(NumberUtils.isParsable(userInput))
then
    insert(new ConfidenceResult(EventNames.NAVIGATE, 0.5));
end