package core_rules.value_display

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.shared.display.ListDisplay
import at.jku.dke.inga.rules.models.ValueDisplayServiceModel

// ------------------------------------ RULES ---------------------------------------
rule "Select cubes"
    agenda-group "value-display-determination"
when
    $model : ValueDisplayServiceModel(operation == EventNames.NAVIGATE_CUBE_SELECT)
then
    insert(new ListDisplay("selectCube", $model.getLocale(), $model.getCubeRepository().getLabelsByLang($model.getLanguage())));
end