package at.jku.dke.inga.rules

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.inga.shared.operations.Operation
import at.jku.dke.inga.rules.models.ResolveOperationsDataModel

// ------------------------------ MEASURE OPERATIONS --------------------------------
rule "'Add Measure' - if at least one measure is available in the cube for selection"
    agenda-group "operation-determination"
when
    $model : ResolveOperationsDataModel(notSelectedMeasures.isEmpty() == false)
then
    insert(new Operation(EventNames.NAVIGATE_MEASURE_ADD, $model.getLocale(), 10));
end

rule "'Refocus Measure' - if at least one measure is available"
    agenda-group "operation-determination"
when
    $as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    $model : ResolveOperationsDataModel(notSelectedMeasures.isEmpty() == false, analysisSituation == $as)
then
    insert(new Operation(EventNames.NAVIGATE_MEASURE_REFOCUS, $model.getLocale(), 11));
end

//rule "'Move Down To Measure' - if at least one measure selected which has children"
//    agenda-group "operation-determination"
//when
//    // TODO
//then
//    insert(new Operation(EventNames.NAVIGATE_MEASURE_MOVE_DOWN, $model.getLocale(), 12));
//end
//
//rule "'Move Up To Measure' - if at least one measure selected which has parents"
//    agenda-group "operation-determination"
//when
//    // TODO
//then
//    insert(new Operation(EventNames.NAVIGATE_MEASURE_MOVE_UP, $model.getLocale(), 13));
//end

rule "'Drop Measure' - if at least one measure is selected"
    agenda-group "operation-determination"
when
    $as : NonComparativeAnalysisSituation(measures.isEmpty() == false)
    $model : ResolveOperationsDataModel(analysisSituation == $as)
then
    insert(new Operation(EventNames.NAVIGATE_MEASURE_DROP, $model.getLocale(), 14));
end