package at.jku.dke.inga.rules

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.rules.models.OperationDeterminationServiceModel
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.rules.helpers.ConfidenceResult
import org.apache.commons.lang3.math.NumberUtils

// ------------------------------------ RULES ---------------------------------------
rule "Resolve Operation"
    agenda-group "operation-determination"
    salience 1
when
    $model : OperationDeterminationServiceModel(NumberUtils.isParsable(userInput), possibleOperations.containsKey(NumberUtils.createInteger(userInput)))
then
    insert(new ConfidenceResult($model.getPossibleOperations().get(NumberUtils.createInteger($model.getUserInput())).getEventName(), 1.0));
end

rule "Invalid Operation Number"
    agenda-group "operation-determination"
    salience 2
when
    $model : OperationDeterminationServiceModel(!NumberUtils.isParsable(userInput) || !possibleOperations.containsKey(NumberUtils.createInteger(userInput)))
then
    insert(new ConfidenceResult(EventNames.INVALID_INPUT, 1.0));
end