package at.jku.dke.inga.rules

// ------------------------------------ IMPORT --------------------------------------
import at.jku.dke.inga.shared.models.NonComparativeAnalysisSituation
import at.jku.dke.inga.shared.EventNames
import at.jku.dke.inga.rules.models.SetValueServiceModel
import at.jku.dke.inga.rules.models.SetStringValueServiceModel
import at.jku.dke.inga.rules.models.SetTwoStringValueServiceModel

// ------------------------------------ RULES ---------------------------------------
rule "Add measure"
    agenda-group "set-value"
when
    $as : NonComparativeAnalysisSituation()
    $model : SetStringValueServiceModel(operation == EventNames.NAVIGATE_MEASURE_ADD, analysisSituation == $as)
then
    $as.addMeasure($model.getValue());
end

rule "Drop measure"
    agenda-group "set-value"
when
    $as : NonComparativeAnalysisSituation()
    $model : SetStringValueServiceModel(operation == EventNames.NAVIGATE_MEASURE_DROP, analysisSituation == $as)
then
    $as.removeMeasure($model.getValue());
end

rule "Refocus measure"
    agenda-group "set-value"
when
    $as : NonComparativeAnalysisSituation()
    $model : SetTwoStringValueServiceModel(operation == EventNames.NAVIGATE_MEASURE_REFOCUS, analysisSituation == $as)
then
    $as.removeMeasure($model.getValue().getLeft());
    $as.addMeasure($model.getValue().getRight());
end